# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('filter_title', models.CharField(max_length=250)),
                ('filter_description', models.TextField()),
                ('filter_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250)),
                ('image_description', models.TextField()),
                ('image_file', models.FileField(upload_to='')),
            ],
        ),
    ]
