# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170522_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='filter',
            name='filter_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(default=''),
        ),
    ]
