# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='iterations',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='session',
            name='output_image_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='filter',
            name='filter_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
