# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170523_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='output_image_file',
        ),
    ]
