# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_session_output_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
    ]
